config/routes.rb
Rails.application.routes.draw do

  get 'stats/show', :path => 'stats'
  root to: redirect('stats')

  resources :taxis
  resources :rides

end

app/models/ride.rb
class Ride < ActiveRecord::Base

  address_regex = /\A[\p{L}0-9 ]+[\p{L}0-9\/]+, ?[\p{L}Z ]+, ?[\p{L} ]+\z/

  attr_accessor :start_address, :destination_address

  belongs_to :taxi

  validates_presence_of :date, :taxi
  validates :distance, :price, :numericality => {:greater_than_or_equal_to => 0}
  validates :start_address, :destination_address, format: {with: address_regex, message: 'is not valid'}

  public
  def taxi_name
    taxi ? taxi.name : '-'
  end


  def formatted_date
    ApplicationController.helpers.formatted_date(date)
  end


  def self.fetch_rides(today)
    Ride.where(date: today.beginning_of_month..today)
        .order(:date)
        .includes(:taxi)
        .all
        .group_by { |ride| ride.date }
  end

end

app/models/taxi.rb
class Taxi < ActiveRecord::Base

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end


  # GET /rides/1
  # GET /rides/1.json
  def show
  end


  # GET /rides/new
  def new
    @ride = Ride.new
  end


  # GET /rides/1/edit
  def edit
  end


  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html do
          flash[:notice] = 'Ride was successfully created.'
          redirect_to action: 'new'
        end
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ride
    @ride = Ride.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def ride_params
    params.require(:ride).permit(:start_address, :destination_address, :price, :distance, :date, :taxi_id)
  end
end

app/controllers/stats_controller.rb
require 'set'
class StatsController < ApplicationController
  include ApplicationHelper

  def show
    today = Date.today
    set_week_stats(today)
    set_month_stats(today)
  end


  def set_week_stats(today)
    @week_distance = 0
    @week_price = 0

    Ride.where(:date => today.beginning_of_week..today).all.each do |ride|
      @week_distance += ride.distance
      @week_price += ride.price
    end
  end


  def set_month_stats(today)
    @month_stats = {}
    Ride.fetch_rides(today)
        .each do |day, rides|

      distance_sum = 0
      price_sum = 0
      taxis = Set.new

      rides.each do |ride|
        distance_sum += ride.distance
        price_sum += ride.price
        taxis.add(ride.taxi.name) if ride.taxi
      end

      @month_stats[day] = {
          day: formatted_date(day),
          distance_sum: distance_sum,
          avg_distance: distance_sum/rides.size,
          avg_price: price_sum/rides.size,
          taxis: join_names(taxis)}
    end
  end


  def join_names(taxis)
    taxis.to_a.sort.join(', ')
  end

end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  before_action :set_taxi, only: [:show, :edit, :update, :destroy]

  # GET /taxis
  # GET /taxis.json
  def index
    @taxis = Taxi.all
  end

  # GET /taxis/1
  # GET /taxis/1.json
  def show
  end

  # GET /taxis/new
  def new
    @taxi = Taxi.new
  end

  # GET /taxis/1/edit
  def edit
  end

  # POST /taxis
  # POST /taxis.json
  def create
    @taxi = Taxi.new(taxi_params)

    respond_to do |format|
      if @taxi.save
        format.html { redirect_to @taxi, notice: 'Taxi was successfully created.' }
        format.json { render :show, status: :created, location: @taxi }
      else
        format.html { render :new }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxis/1
  # PATCH/PUT /taxis/1.json
  def update
    respond_to do |format|
      if @taxi.update(taxi_params)
        format.html { redirect_to @taxi, notice: 'Taxi was successfully updated.' }
        format.json { render :show, status: :ok, location: @taxi }
      else
        format.html { render :edit }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxis/1
  # DELETE /taxis/1.json
  def destroy
    @taxi.destroy
    respond_to do |format|
      format.html { redirect_to taxis_url, notice: 'Taxi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taxi
      @taxi = Taxi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taxi_params
      params.require(:taxi).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    if date
      date.strftime("%B, #{date.day.ordinalize}")
    else
      '-'
    end
  end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/taxis_helper.rb
module TaxisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riderank</title>
  <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Rubik:300' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.png" %>
</head>
<body>
<div id="menu-bg"></div>
<div id="banner">
  Riderank
</div>
<div id="taxi_line"></div>
<div id="columns">
  <div id="side">
    <ul>
      <li><%= link_to 'Stats', stats_show_path %></li>
      <li><%= link_to 'Rides', rides_path %></li>
      <li><%= link_to 'Taxis', taxis_path %></li>
    </ul>
  </div>
  <div id="main">
    <% if flash[:notice] %>
        <p id="notice"><%= notice %></p>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/rides/_form.html.erb
<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyC5rhvfNGL7HxDPKdhGKp_Q-BjdCxCJwQA' %>
<div class="form">
  <%= form_for(@ride) do |f| %>
      <% if @ride.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

            <ul>
              <% @ride.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :start_address %><br>
        <%= f.text_field :start_address, :placeholder => 'Street Number, City, Country' %>
      </div>
      <div class="field">
        <%= f.label :destination_address %><br>
        <%= f.text_field :destination_address, :placeholder => 'Street Number, City, Country' %>
      </div>
      <div class="field">
        <%= f.label :distance %><br>
        <%= f.text_field :distance %> km
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price %> EUR
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
      <div class="field">
        <%= f.label :taxi %><br>
        <%= f.collection_select :taxi_id, Taxi.order(:name), :id, :name, prompt: true, include_blank: false %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<h1>Rides</h1>

<table>
  <thead>
  <tr>
    <th>Price</th>
    <th>Distance</th>
    <th>Date</th>
    <th>Taxi</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rides.each do |ride| %>
      <tr class="<%= cycle('row_odd', 'row_even') %>">
        <td><%= number_with_precision(ride.price, :precision => 2) %> EUR</td>
        <td><%= number_with_precision(ride.distance, :precision => 3) %> km</td>
        <td><%= ride.formatted_date %></td>
        <td><%= ride.taxi_name %></td>

        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p>
  <strong>Price:</strong>
  <%= @ride.price %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @ride.distance %>
</p>

<p>
  <strong>Date:</strong>
  <%= @ride.date %>
</p>

<p>
  <strong>Taxi:</strong>
  <%= @ride.taxi_name %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/stats/show.html.erb
<h1>Statistics</h1>
<div id="week_stats">
  <p>Distance in current week:  <%= @week_distance %> km</p>
  <p>Money spent in current week:  <%= @week_price %> EUR</p>
</div>

<table>
  <thead>
  <tr>
    <th>Day</th>
    <th>Rides sum</th>
    <th>Avg. ride</th>
    <th>Avg. price</th>
    <th>Taxis</th>
  </tr>
  </thead>
  <tbody>
  <% @month_stats.each do |day, stats| %>
      <tr class="<%= cycle('row_odd', 'row_even') %>">
        <td> <%= stats[:day] %></td>
        <td> <%= number_with_precision(stats[:distance_sum], :precision => 3) %> km</td>
        <td> <%= number_with_precision(stats[:avg_distance], :precision => 3) %> km</td>
        <td> <%= number_with_precision(stats[:avg_price], :precision => 2) %> EUR</td>
        <td> <%= stats[:taxis] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/taxis/_form.html.erb
<div class="form">
  <%= form_for(@taxi) do |f| %>
      <% if @taxi.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@taxi.errors.count, "error") %> prohibited this taxi from being saved:</h2>

            <ul>
              <% @taxi.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/taxis/edit.html.slim
h1 Editing Taxi

= render 'form'

= link_to 'Show', @taxi
= link_to 'Back', taxis_path

app/views/taxis/index.html.erb
<h1>Taxis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taxis.each do |taxi| %>
      <tr class="<%= cycle('row_odd', 'row_even') %>">
        <td><%= taxi.name %></td>
        <td><%= link_to 'Show', taxi %></td>
        <td><%= link_to 'Edit', edit_taxi_path(taxi) %></td>
        <td><%= link_to 'Destroy', taxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taxi', new_taxi_path %>

app/views/taxis/new.html.erb
<h1>New Taxi</h1>

<%= render 'form' %>

<%= link_to 'Back', taxis_path %>

app/views/taxis/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @taxi.name %>
</p>

<%= link_to 'Edit', edit_taxi_path(@taxi) %> |
<%= link_to 'Back', taxis_path %>